# Generated by Django 3.0.8 on 2020-07-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Nickname',
        ),
    ]
