# Generated by Django 3.0.7 on 2020-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
