# Generated by Django 3.0.8 on 2020-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
