# Generated by Django 3.0.8 on 2020-07-25 05:13

from django.db import migrations, models
import halls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_request_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(blank=True, upload_to='files/resume', validators=[halls.validators.validate_file_extension]),
        ),
    ]
