# Generated by Django 3.0.8 on 2020-07-25 06:10

from django.db import migrations, models
import halls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_auto_20200725_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(upload_to='files/', validators=[halls.validators.validate_file_question]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_file',
            field=models.FileField(blank='True', upload_to='files/payments', validators=[halls.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solutionfile',
            field=models.FileField(blank='True', upload_to='files/solutions', validators=[halls.validators.validate_file_solution]),
        ),
    ]
